

```{r}
setwd("C:/Users/csiamof/Desktop/")
#need to install and load R.matlab
library(R.matlab)
library(gridExtra)
library(ggplot2)
library(gtable)
library(gtools)
library(plyr)
library(utils)
mydata <- readMat('Imaging_1hrsToxo.mat') #this reads in the data file
mydata = lapply(mydata, unlist, use.names = F) #this won't look like it does anything
mydata <- lapply(mydata, `length<-`, max(lengths(mydata)))
df1 <- as.data.frame(mydata) #this creats the first data frame 
df1$Group <- rep("Toxo", nrow(df1)) 
df1$Time <- rep("1 hrs", nrow(df1)) 

mydata2 <- readMat("Imaging_1hrWithoutToxo.mat")
mydata2 <- lapply(mydata2, `length<-`, max(lengths(mydata2))) 
df2 <- as.data.frame(mydata2)
df2$Group <- rep("Media + Inhibitor", nrow(df2)) 
df2$Time <- rep("1 hrs", nrow(df2)) 

mydata3 <- readMat("Imaging_6hrsToxo.mat")
mydata3 <- lapply(mydata3, `length<-`, max(lengths(mydata3))) 
df3 <- as.data.frame(mydata3)
df3$Group <- rep("Toxo", nrow(df3)) 
df3$Time <- rep("6 hrs", nrow(df3)) 

mydata4 <- readMat("Imaging_6hrsWithoutToxo.mat")
mydata4 <- lapply(mydata4, `length<-`, max(lengths(mydata4)))
df4 <- as.data.frame(mydata4)
df4$Group <- rep("Media + Inhibitor", nrow(df4)) 
df4$Time <- rep("6 hrs", nrow(df4))

mydata5 <- readMat("90mpi_MediaInhibitor.mat")
mydata5 <- lapply(mydata5, `length<-`, max(lengths(mydata5)))
df5 <- as.data.frame(mydata5)
df5$Group <- rep("Media + Inhibitor", nrow(df5))
df5$Time <- rep("90 min", nrow(df5)) 

mydata6 <- readMat("90mpi_MediaOnly.mat")
mydata6 <- lapply(mydata6, `length<-`, max(lengths(mydata6)))
df6 <- as.data.frame(mydata6)
df6$Group <- rep("Media", nrow(df6))
df6$Time <- rep("90 min", nrow(df6)) 

mydata7 <- readMat("90mpi_Toxo.mat")
mydata7 <- lapply(mydata7, `length<-`, max(lengths(mydata7)))
df7 <- as.data.frame(mydata7)
df7$Group <- rep("Toxo", nrow(df7))
df7$Time <- rep("90 min", nrow(df7)) 

mydata8 <- readMat("90mpi_ToxoInhibitor.mat")
mydata8 <- lapply(mydata8, `length<-`, max(lengths(mydata8)))
df8 <- as.data.frame(mydata8)
df8$Group <- rep("Toxo + Inhibitor", nrow(df8))
df8$Time <- rep("90 min", nrow(df8)) 

newdata <- rbind.fill(df1, df2, df3) 

newdata$Group <- with(newdata, relevel(as.factor(Group), c("Media")))
newdata$Time <- with(newdata, relevel(as.factor(Time), c("90 min")))

newdata_cells <- newdata[,c(1,2,3,4,5,6,7,8,9,10,11,12,14,27,28)]
newdata_toxo <- newdata[,c(13,15,16,17,18,19,20,21,22,23,24,25,26,27,28)]

newdata_cells$has.toxo.out <- with(newdata, relevel(as.factor(has.toxo.out), c("2")))
newdata_toxo$in.cell.out <- with(newdata, relevel(as.factor(in.cell.out), c("2")))

toxdata <-  subset(newdata_cells, Group == "Toxo")
toxdata2 <-  subset(toxdata, N.a1.out != "NA")

toxinhdata <-  subset(newdata_cells, Group == "Toxo + Inhibitor")
toxinhdata2 <-  subset(toxinhdata, N.a1.out != "NA")

meddata <-  subset(newdata_cells, Group == "Media")
medinhdata <-  subset(newdata_cells, Group == "Media + Inhibitor")

alltoxo <- rbind(toxdata,toxinhdata)
alltoxo <- subset(alltoxo, !is.na(F.a1.out))
allctrl <- rbind(meddata,medinhdata)
allctrl <- subset(allctrl, !is.na(F.a1.out))


newdata_infected <- subset(toxinhdata2, has.toxo.out == "1")
newdata_notinfected <- subset(newdata, has.toxo.out == "2")

newdata_toxo <- subset(newdata_toxo, !is.na(tF.a1.out))

write.csv(newdata_toxo,'031819_toxoplasma.csv')

